### ISSUE TITLE
Missing transtech_directory/forms.py

### ISSUE THREAD

**Issue by nanuxbe** [nanuxbe/transtech-directory#11]
I will quickly create the file with a stub class in it to get going again
@JustinWingChungHui  can you take a look at your local repo and see if you have a working copy of the file you could commit? Thanks :-)

**Comment by JustinWingChungHui** [comment]
Ok I'll have a look!

**Comment by nanuxbe** [comment]
Thanks :-) (I figured it got forgotten due to the "bomb event")
